[build]
builder = "dockerfile"
watchPatterns = ["standalone-express-app/**"]

[deploy]
healthcheckPath = "/healthcheck"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
internal_port = 3000
protocol = "tcp"

  [[services.ports]]
  handlers = ["http"]
  port = 80

  [[services.ports]]
  handlers = ["tls", "http"]
  port = 443
  
[environments.production]
numReplicas = 1