[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["./module-type-fix.sh", "npx vite build", "cp direct-server.cjs /app/"]

[start]
cmd = "node direct-server.cjs"