[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["./module-type-fix.sh", "npx vite build", "cp app-entry.js /app/", "cp telegram-webapp-server.js /app/"]

[start]
cmd = "node telegram-webapp-server.js"