[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["./module-type-fix.sh", "npx vite build", "cp app-entry.js /app/", "cp index.cjs /app/"]

[start]
cmd = "node index.cjs"