[phases.setup]
nixPackages = ["nodejs_20"]
aptPkgs = ["curl"]

[phases.build]
cmds = ["npm ci --production", "npm run postinstall --if-present"]

[phases.cleanup]
cmds = ["rm -rf .git", "rm -rf node_modules/.cache"]

[start]
cmd = "node full-server.cjs"