# Максимально простая конфигурация
[build]
builder = "NIXPACKS"

[deploy]
# Полностью отключаем проверку здоровья
healthcheckEnabled = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "NODE_ENV=production node --enable-source-maps dist/index.js"
sleepApplication = false

[env]
PORT = "8080"
NODE_ENV = "production"