# Максимально простая конфигурация
[build]
builder = "NIXPACKS"
buildCommand = "./module-type-fix.sh && npx vite build"

[deploy]
# Используем прямой сервер
healthcheckEnabled = true
healthcheckPath = "/healthcheck"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "node direct-server.js"
sleepApplication = false

[env]
PORT = "8080"
NODE_ENV = "production"
WEB_APP_URL = "https://esentioshop-production-up.up.railway.app"