[build]
builder = "DOCKERFILE"
watchPatterns = ["dist/**", "server/**", "client/**"]
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[runtime]
environmentVariables = ["PGDATABASE", "PGUSER", "PGPASSWORD", "PGHOST", "PGPORT"]