[build]
builder = "NIXPACKS"

[deploy]
# По умолчанию Railway использует Procfile, указывать команду старта не нужно
restartPolicyType = "ON_FAILURE"
# Полностью отключаем проверку здоровья
healthcheckEnabled = false

[env]
NODE_ENV = "production"