# Максимально простая конфигурация
[build]
builder = "NIXPACKS"
buildCommand = "npx vite build"

[deploy]
# Полностью отключаем проверку здоровья
healthcheckEnabled = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "node app-entry.js"
sleepApplication = false

[env]
PORT = "8080"
NODE_ENV = "production"