# Максимально простая конфигурация
[build]
builder = "NIXPACKS"
buildCommand = "node railway-build.js"

[deploy]
# Полностью отключаем проверку здоровья
healthcheckEnabled = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "node direct-server.js"
sleepApplication = false

[env]
PORT = "8080"
NODE_ENV = "production"