# Максимально простая конфигурация
[build]
builder = "DOCKERFILE"

[deploy]
# Полностью отключаем проверку здоровья
healthcheckEnabled = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
sleepApplication = false

[env]
PORT = "8080"
NODE_ENV = "production"