[build]
builder = "NIXPACKS"
nixpacksVersion = "1.17.0"

[deploy]
startCommand = "node full-server.cjs"
healthcheckPath = "/healthcheck"
healthcheckTimeout = 300
healthcheckInterval = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
sleepApplication = false  # Очень важно, чтобы приложение не перешло в спящий режим

[deploy.envs]
PORT = { default = 8080 }
NODE_ENV = { default = "production" }