# Максимально простая конфигурация
[build]
builder = "NIXPACKS"
buildCommand = "./module-type-fix.sh && npx vite build"

[deploy]
# Полностью отключаем проверку здоровья
healthcheckEnabled = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "node index.cjs"
sleepApplication = false

[env]
PORT = "8080"
NODE_ENV = "production"
WEB_APP_URL = "https://esentioshop-production-up.up.railway.app"