[build]
builder = "nixpacks"
# Простой сервер без webpack/vite/etc
buildCommand = "echo 'No build required for simple server'"

[deploy]
# Запускаем минимальный сервер без зависимостей от других модулей
startCommand = "node index.cjs"
healthcheckPath = "/healthcheck"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
internal_port = 3000
protocol = "tcp"

  [[services.ports]]
  handlers = ["http"]
  port = 80

  [[services.ports]]
  handlers = ["tls", "http"]
  port = 443
  
[environments.production]
numReplicas = 1