# Максимально простая конфигурация
[build]
builder = "NIXPACKS"
buildCommand = "./module-type-fix.sh && npx vite build"

[deploy]
# Полноценный сервер с сохранением дизайна
healthcheckEnabled = true
healthcheckPath = "/healthcheck"  
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 10
startCommand = "node full-server.cjs"
sleepApplication = false

[env]
PORT = "8080"
NODE_ENV = "production"
WEB_APP_URL = "https://esentioshop-production-up.up.railway.app"