[build]
builder = "NIXPACKS"
nixpacksVersion = "1.17.0"

[deploy]
startCommand = "node minimal-app.cjs"
healthcheckPath = "/healthcheck"
healthcheckTimeout = 300
healthcheckInterval = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
sleepApplication = false

[deploy.envs]
PORT = { default = 8080 }
NODE_ENV = { default = "production" }