[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
sleepApplication = false

[runtime]
autorestart = true
environmentVariables = ["PGDATABASE", "PGUSER", "PGPASSWORD", "PGHOST", "PGPORT"]