[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "bash .railway/start.sh"
healthcheckCommand = "node .railway/healthcheck.js"
healthcheckTimeout = 300
healthcheckIntervalSeconds = 15
readinessTimeoutSeconds = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
sleepApplication = false

[runtime]
autorestart = true
environmentVariables = ["PGDATABASE", "PGUSER", "PGPASSWORD", "PGHOST", "PGPORT"]