# Максимально простая конфигурация
[build]
builder = "NIXPACKS"

[deploy]
# Полностью отключаем проверку здоровья
healthcheckEnabled = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "npm run start"
sleepApplication = false

[env]
PORT = "8080"
NODE_ENV = "production"