# Оптимизированная конфигурация для Railway
[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
# Включаем healthcheck через собственный скрипт
healthcheckPath = "/"
healthcheckTimeout = 10
restartPolicyMaxRetries = 5
restartPolicyType = "ON_FAILURE"
sleepApplication = false
startCommand = "bash start.sh"